# ac
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ac.8
complete -c ac -s d -d 'Display the connect times in 24 hour chunks'
complete -c ac -s p -d 'Print individual users\' totals'
complete -c ac -s t -d 'Only do accounting logins on certain ttys'
complete -c ac -s w -d 'Read connect time data from wtmp instead of the default, reading from the log…'

