# bc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/bc.1
complete -c bc -s g -l global-stacks
complete -c bc -s h -l help
complete -c bc -s i -l interactive
complete -c bc -s l -l mathlib
complete -c bc -s P -l no-prompt
complete -c bc -s R -l no-read-prompt
complete -c bc -s q -l quiet
complete -c bc -s v -s V -l version -d 'This is a **non-portable extension**'
complete -c bc -s s -l standard
complete -c bc -s w -l warn
complete -c bc -s e -l expression
complete -c bc -s f -l file
complete -c bc -o s/--standard -o w/--warn -d 'options are given since they are not part of the library defined by the stand…'

