# bsqlodbc
# Autogenerated from man page /opt/homebrew/share/man/man1/bsqlodbc.1
complete -c bsqlodbc -s U -d 'Database server login name'
complete -c bsqlodbc -s P -d 'Database server password'
complete -c bsqlodbc -s S -d 'Database server to which to connect'
complete -c bsqlodbc -s D -d 'Database to use'
complete -c bsqlodbc -s i -d 'Name of script file, containing SQL'
complete -c bsqlodbc -s o -d 'Name of output file, holding result data'
complete -c bsqlodbc -s e -d 'Name of file for errors'
complete -c bsqlodbc -s t -d 'Specifies the field terminator.  Default is two spaces ( \\ )'
complete -c bsqlodbc -s h -d 'Print column headers with the data to the same file'
complete -c bsqlodbc -s q -d 'Do not print column metadata, return status, or rowcount.  Overrides h'
complete -c bsqlodbc -s v -d 'Verbose mode, for more information about the ODBC interaction'
complete -c bsqlodbc -s V -d 'Specify ODBC version (2 or 3)'

