# bsqldb
# Autogenerated from man page /opt/homebrew/share/man/man1/bsqldb.1
complete -c bsqldb -s D -d 'Database to use'
complete -c bsqldb -s H -d 'hostname Override name of client sent to server'
complete -c bsqldb -s P -d 'Database server password'
complete -c bsqldb -s S -d 'Database server to which to connect'
complete -c bsqldb -s U -d 'Database server login name'
complete -c bsqldb -s e -d 'Name of file for errors'
complete -c bsqldb -s h -d 'Print column headers with the data to the same file'
complete -c bsqldb -s i -d 'Name of script file, containing SQL'
complete -c bsqldb -s o -d 'Name of output file, holding result data'
complete -c bsqldb -s q -d 'Do not print column metadata, return status, or rowcount.  Overrides h Ns'
complete -c bsqldb -s t -d 'Specifies the field terminator.  Default is two spaces (\' \')'
complete -c bsqldb -s v -d 'Verbose mode, for more information about the DB-Library interaction'
complete -c bsqldb -s R -d 'Specify pivot trasformation'

