# comp_err
# Autogenerated from man page /opt/homebrew/share/man/man1/comp_err.1
complete -c comp_err -l help
complete -c comp_err -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c comp_err -l charset
complete -c comp_err -s C -d 'The character set directory.  The default is . /sql/share/charsets.  oc o 2'
complete -c comp_err -l debug
complete -c comp_err -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:O,file_name'
complete -c comp_err -l debug-info
complete -c comp_err -s T -d 'Print some debugging information when the program exits.  oc o 2. 3'
complete -c comp_err -l errmsg-file
complete -c comp_err -s H -d 'The name of the error message file.  The default is mysqld_errmsg. h'
complete -c comp_err -l header-file
complete -c comp_err -l in-file
complete -c comp_err -s F -d 'The name of the input file.  The default is . /share/errmsg-utf8. txt'
complete -c comp_err -l in-file-errlog -d and
complete -c comp_err -l in-file-toclient -d 'options.  oc o 2. 3'
complete -c comp_err -s e -d 'The name of the input file that defines error messages intended to be written…'
complete -c comp_err -s c -d 'The name of the input file that defines error messages intended to be written…'
complete -c comp_err -l name-file
complete -c comp_err -s N -d 'The name of the error name file.  The default is mysqld_ername. h.  oc o 2. 3'
complete -c comp_err -l out-dir
complete -c comp_err -s D -d 'The name of the output base directory.  The default is . /sql/share/.  oc o 2'
complete -c comp_err -l out-file
complete -c comp_err -s O -d 'The name of the output file.  The default is errmsg. sys.  oc o 2. 3'
complete -c comp_err -l version
complete -c comp_err -s V -d 'Display version information and exit'

