# corelist5.30
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/corelist5.30.1
complete -c 'corelist5.30' -s a -d 'lists all versions of the given module (or the matching modules, in case you …'
complete -c 'corelist5.30' -s d -d 'finds the first perl version where a module has been released by date, and no…'
complete -c 'corelist5.30' -l diff -d 'Given two versions of perl, this prints a human-readable table of all module …'
complete -c 'corelist5.30' -s '?' -o help -d 'help! help! help! to see more help, try --man'
complete -c 'corelist5.30' -o man -d 'all of the help'
complete -c 'corelist5.30' -s v -d 'lists all of the perl release versions we got the CoreList for'
complete -c 'corelist5.30' -s r -d 'lists all of the perl releases and when they were released '
complete -c 'corelist5.30' -l utils -d 'lists the first version of perl each named utility program was released with '
complete -c 'corelist5.30' -l feature -s f -d 'lists the first version bundle of each named feature given'

