# datacopy
# Autogenerated from man page /opt/homebrew/share/man/man1/datacopy.1
complete -c datacopy -s t -d 'Truncate target table before loading data'
complete -c datacopy -s a -d 'Append data to target table'
complete -c datacopy -s c -d 'Create the target table with the same schema as the source table'
complete -c datacopy -s b -d 'The number of rows per batch of data copied'
complete -c datacopy -s p -d 'The number of bytes, per network packet, sent to and from the servers'
complete -c datacopy -s T -d 'Specify size of TEXT/IMAGE column from network'
complete -c datacopy -s v -d 'Produce verbose output, including diagnostic timings'
complete -c datacopy -s d -d 'Produce freetds TDSDUMP output.  (Serious debug only!)'
complete -c datacopy -s S -d 'The connection information for the source server and the location/name of the…'
complete -c datacopy -s D -d 'The connection information for the destination server and the location/name o…'
complete -c datacopy -s E -d 'Keep identity values'

