# dc
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dc.1
complete -c dc -s f -l file -d 'and exit'
complete -c dc -s e -d 'they can just simply add -e q as the last command-line argument or define the…'
complete -c dc -s h -l help
complete -c dc -s v -s V -l version
complete -c dc -s i -l interactive
complete -c dc -s P -l no-prompt
complete -c dc -s R -l no-read-prompt
complete -c dc -s x -l extended-register
complete -c dc -l expression

