# defncopy
# Autogenerated from man page /opt/homebrew/share/man/man1/defncopy.1
complete -c defncopy -s U -d 'database server login name'
complete -c defncopy -s P -d 'database server password'
complete -c defncopy -s S -d 'database server to which to connect'
complete -c defncopy -s D -d 'database to use'
complete -c defncopy -s i -d 'a script to apply to the database.  Not currently implemented'
complete -c defncopy -s o -d 'a file to hold the script, defaults to standard output'
complete -c defncopy -s v -d 'Show version information and copyright notice'

