# dyld_usage
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/dyld_usage.1
complete -c dyld_usage -s e -d 'Exclude the specified list of pids and commands from the sample, and exclude …'
complete -c dyld_usage -s h -d 'Display usage information and exit'
complete -c dyld_usage -s R -d 'Specify a raw trace file to process'
complete -c dyld_usage -s t -d 'Specify timeout in seconds (for use in automated tools)'
complete -c dyld_usage -s j -d 'Display output in JSON format'

