# ed
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ed.1
complete -c ed -s s -d 'Suppress diagnostics'
complete -c ed -s p -d 'Specify a command prompt.  This may be toggled on and off with the P command'

