# git-receive-pack
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-receive-pack.1
complete -c git-receive-pack -l http-backend-info-refs -d 'Used by git-http-backend(1) to serve up $GIT_URL/info/refs?service=git-receiv…'

