# git-version
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-version.1
complete -c git-version -l build-options -d 'Include additional information about how git was built for diagnostic purposes'

