# glibtoolize
# Autogenerated from man page /opt/homebrew/share/man/man1/glibtoolize.1
complete -c glibtoolize -s c -l copy -d 'copy files rather than symlinking them'
complete -c glibtoolize -l debug -d 'enable verbose shell tracing'
complete -c glibtoolize -s n -l dry-run -d 'print commands rather than running them'
complete -c glibtoolize -s f -l force -d 'replace existing files'
complete -c glibtoolize -s i -l install -d 'copy missing auxiliary files'
complete -c glibtoolize -l ltdl -d 'install libltdl sources [default: libltdl]'
complete -c glibtoolize -l no-warnings -d 'equivalent to \'-Wnone\''
complete -c glibtoolize -l nonrecursive -d 'prepare ltdl for non-recursive make'
complete -c glibtoolize -s q -l quiet -d 'work silently'
complete -c glibtoolize -l recursive -d 'prepare ltdl for recursive make'
complete -c glibtoolize -l subproject -d 'prepare ltdl to configure and build independently'
complete -c glibtoolize -s v -l verbose -d 'verbosely report processing'
complete -c glibtoolize -l version -d 'print version information and exit'
complete -c glibtoolize -s W -l warnings -d 'report the warnings falling in CATEGORY [all]'
complete -c glibtoolize -s h -l help -d 'print short or long help message . SS "Warning categories include:"'

