# glibtool
# Autogenerated from man page /opt/homebrew/share/man/man1/glibtool.1
complete -c glibtool -l config -d 'show all configuration variables'
complete -c glibtool -l debug -d 'enable verbose shell tracing'
complete -c glibtool -s n -l dry-run -d 'display commands without modifying any files'
complete -c glibtool -l features -d 'display basic configuration information and exit'
complete -c glibtool -l mode -d 'use operation mode MODE'
complete -c glibtool -l no-warnings -d 'equivalent to \'-Wnone\''
complete -c glibtool -l preserve-dup-deps -d 'don\'t remove duplicate dependency libraries'
complete -c glibtool -l quiet -l silent -d 'don\'t print informational messages'
complete -c glibtool -l tag -d 'use configuration variables from tag TAG'
complete -c glibtool -s v -l verbose -d 'print more informational messages than default'
complete -c glibtool -l version -d 'print version information'
complete -c glibtool -s W -l warnings -d 'report the warnings falling in CATEGORY [all]'
complete -c glibtool -s h -l help -l help-all -d 'print short, long, or detailed help message '

