# gnutls-certtool
# Autogenerated from man page /opt/homebrew/share/man/man1/gnutls-certtool.1
complete -c gnutls-certtool -l generate-privkey -l generate-dh-params
complete -c gnutls-certtool -l load-ca-certificate -d '$ certtool --load-ca-certificate ca. pem    --load-certificate cert'

