# ibd2sdi
# Autogenerated from man page /opt/homebrew/share/man/man1/ibd2sdi.1
complete -c ibd2sdi -l help
complete -c ibd2sdi -s h -d 'Display a help message and exit.  For example: Usage: '
complete -c ibd2sdi -l ------------------------------- -l -------------------------------------- -d 'debug                             (No default value) dump-file               …'
complete -c ibd2sdi -l version
complete -c ibd2sdi -s v -d 'Display version information and exit.  For example: ibd2sdi  Ver 8. 0'
complete -c ibd2sdi -l debug
complete -c ibd2sdi -s '#' -d 'Prints a debug log.  For debug options, refer to Section 5. 9'
complete -c ibd2sdi -l dump-file
complete -c ibd2sdi -s d -d 'Dumps serialized dictionary information (SDI) into the specified dump file'
complete -c ibd2sdi -l skip-data
complete -c ibd2sdi -s s -d 'Skips retrieval of data field values from the serialized dictionary informati…'
complete -c ibd2sdi -l id
complete -c ibd2sdi -s i -d 'Retrieves serialized dictionary information (SDI) matching the specified tabl…'
complete -c ibd2sdi -l type
complete -c ibd2sdi -s t -d 'Retrieves serialized dictionary information (SDI) matching the specified obje…'
complete -c ibd2sdi -l strict-check
complete -c ibd2sdi -s c -d 'Specifies a strict checksum algorithm for validating the checksum of pages th…'
complete -c ibd2sdi -l no-check
complete -c ibd2sdi -s n -d 'Skips checksum validation for pages that are read.  ibd2sdi --no-check '
complete -c ibd2sdi -l pretty
complete -c ibd2sdi -s p -d 'Outputs SDI data in JSON pretty print format.  Enabled by default'
complete -c ibd2sdi -l skip-pretty -d 'to disable.  ibd2sdi --skip-pretty . /data/test/t1'

