# innochecksum
# Autogenerated from man page /opt/homebrew/share/man/man1/innochecksum.1
complete -c innochecksum -l help
complete -c innochecksum -s '?' -d 'Displays command line help.  Example usage: innochecksum --help oc o 2. 3'
complete -c innochecksum -l info
complete -c innochecksum -s I -d 'Synonym for'
complete -c innochecksum -l version
complete -c innochecksum -s V -d 'Displays version information.  Example usage: innochecksum --version oc o 2'
complete -c innochecksum -l verbose
complete -c innochecksum -s v -d 'Verbose mode; prints a progress indicator to the log file every five seconds'
complete -c innochecksum -l log -d 'verbose mode, run: innochecksum --verbose To turn off verbose mode, run: inno…'
complete -c innochecksum -l count
complete -c innochecksum -s c -d 'Print a count of the number of pages in the file and exit'
complete -c innochecksum -l start-page
complete -c innochecksum -s s -d 'Start at this page number.  Example usage: innochecksum --start-page=600 '
complete -c innochecksum -l end-page
complete -c innochecksum -s e -d 'End at this page number.  Example usage: innochecksum --end-page=700 '
complete -c innochecksum -l page
complete -c innochecksum -s p -d 'Check only this page number.  Example usage: innochecksum --page=701 '
complete -c innochecksum -l strict-check
complete -c innochecksum -s C -d 'Specify a strict checksum algorithm.  Options include innodb, crc32, and none'
complete -c innochecksum -l no-check
complete -c innochecksum -s n -d 'Ignore the checksum verification when rewriting a checksum'
complete -c innochecksum -l write -d 'option.  If the'
complete -c innochecksum -l allow-mismatches
complete -c innochecksum -s a -d 'The maximum number of checksum mismatches allowed before innochecksum termina…'
complete -c innochecksum -s w -d 'Rewrite a checksum.  When rewriting an invalid checksum, the'
complete -c innochecksum -l page-type-summary
complete -c innochecksum -s S -d 'Display a count of each page type in a tablespace'
complete -c innochecksum -l page-type-dump
complete -c innochecksum -s D -d 'Dump the page type information for each page in a tablespace to stderr or std…'
complete -c innochecksum -s l -d 'Log output for the innochecksum tool.  A log file name must be provided'
complete -c innochecksum -l debug -d 'option, which was available in earlier releases'

