# man
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/man.1
complete -c man -s M -d 'Forces a specific colon separated manual path instead of the default search p…'
complete -c man -s P -d 'Use specified pager'
complete -c man -s S -d 'Restricts manual sections searched to the specified colon delimited list'
complete -c man -s a -d 'Display all manual pages instead of just the first found for each page argume…'
complete -c man -s d -d 'Print extra debugging information.  Repeat for increased verbosity'
complete -c man -s f -d 'Emulate whatis 1'
complete -c man -s h -d 'Display short help message and exit'
complete -c man -s k -d 'Emulate apropos 1'
complete -c man -s m -d 'Override the default architecture and machine settings allowing lookup of oth…'
complete -c man -s o -d 'Force use of non-localized manual pages'
complete -c man -s p -d 'Use the list of given preprocessors before running nroff 1 or troff 1'
complete -c man -s t -d 'Send manual page source through troff 1 allowing transformation of the manual…'
complete -c man -s w -d 'Display the location of the manual page instead of the contents of the manual…'
complete -c man -s s -d 'Same as the S option for man'

