# manpath
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/manpath.1
complete -c manpath -s L -d 'Output manual locales list instead of the manual path'
complete -c manpath -s d -d 'Print extra debugging information'
complete -c manpath -s q -d 'Suppresses warning messages'

