# metal-arch
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/metal-arch.1
complete -c metal-arch -o help -d 'Display available options'
complete -c metal-arch -o default -d 'Print the architecture of the default GPU in the machine'
complete -c metal-arch -o name -d 'Print human friendly GPU names'

