# metal-config
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/metal-config.1
complete -c metal-config -o help -d 'Display available options'
complete -c metal-config -o native-archs -d 'Prints all the supported native architectures'
complete -c metal-config -o native-arch-flags -d 'Prints each supported native architecture prefixed with the \\%-arch flag'
complete -c metal-config -o gpu-family -d 'Ignore native architectures not belonging to any of the specified families in…'

