# mknod
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/mknod.8
complete -c mknod -s r -d 'Replace an existing file if its type is incorrect'
complete -c mknod -s R -d 'Replace an existing file if its type is incorrect'
complete -c mknod -s F -d 'Create device nodes that may be used by an operating system which uses device…'
complete -c mknod -s g -d 'Specify the group for the device node'
complete -c mknod -s m -d 'Specify the mode for the device node'
complete -c mknod -s l -d 'List the device drivers configured into the current kernel together with thei…'

