# myisampack
# Autogenerated from man page /opt/homebrew/share/man/man1/myisampack.1
complete -c myisampack -l help
complete -c myisampack -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c myisampack -l backup
complete -c myisampack -s b -d 'Make a backup of each tables data file using the name tbl_name. OLD.  oc o 2'
complete -c myisampack -l character-sets-dir -d 'The directory where character sets are installed.  See Section 10'
complete -c myisampack -l debug
complete -c myisampack -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c myisampack -l force
complete -c myisampack -s f -d 'Produce a packed table even if it becomes larger than the original or if the …'
complete -c myisampack -l join
complete -c myisampack -s j -d 'Join all tables named on the command line into a single packed table big_tbl_…'
complete -c myisampack -l silent
complete -c myisampack -s s -d 'Silent mode.  Write output only when errors occur.  oc o 2. 3'
complete -c myisampack -l test
complete -c myisampack -s t -d 'Do not actually pack the table, just test packing it.  oc o 2. 3'
complete -c myisampack -l tmpdir
complete -c myisampack -s T -d 'Use the named directory as the location where myisampack creates temporary fi…'
complete -c myisampack -l verbose
complete -c myisampack -s v -d 'Verbose mode'
complete -c myisampack -l version
complete -c myisampack -s V -d 'Display version information and exit.  oc o 2. 3'
complete -c myisampack -l wait
complete -c myisampack -s w -d 'Wait and retry if the table is in use'
complete -c myisampack -o rw-rw-r--
complete -c myisampack -o 128 -d 'to 127.  oc o 2. 3'
complete -c myisampack -l unpack -d 'option to myisamchk'

