# myisamlog
# Autogenerated from man page /opt/homebrew/share/man/man1/myisamlog.1
complete -c myisamlog -l log-isam -d option
complete -c myisamlog -s '?'
complete -c myisamlog -s I
complete -c myisamlog -s c
complete -c myisamlog -s f
complete -c myisamlog -s F
complete -c myisamlog -s i
complete -c myisamlog -s o
complete -c myisamlog -s p
complete -c myisamlog -s r
complete -c myisamlog -s R
complete -c myisamlog -s u
complete -c myisamlog -s v
complete -c myisamlog -s w
complete -c myisamlog -s V

