# myisam_ftdump
# Autogenerated from man page /opt/homebrew/share/man/man1/myisam_ftdump.1
complete -c myisam_ftdump -l help
complete -c myisam_ftdump -s h
complete -c myisam_ftdump -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c myisam_ftdump -l count
complete -c myisam_ftdump -s c -d 'Calculate per-word statistics (counts and global weights).  oc o 2. 3'
complete -c myisam_ftdump -l dump
complete -c myisam_ftdump -s d -d 'Dump the index, including data offsets and word weights.  oc o 2. 3'
complete -c myisam_ftdump -l length
complete -c myisam_ftdump -s l -d 'Report the length distribution.  oc o 2. 3'
complete -c myisam_ftdump -l stats
complete -c myisam_ftdump -s s -d 'Report global index statistics'
complete -c myisam_ftdump -l verbose
complete -c myisam_ftdump -s v -d 'Verbose mode.  Print more output about what the program does'

