# mysqld_safe
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqld_safe.1
complete -c mysqld_safe -l mysqld -d or
complete -c mysqld_safe -l mysqld-version -d 'option to mysqld_safe.  You can also use'
complete -c mysqld_safe -l ledir -d 'to indicate the directory where mysqld_safe should look for the server'
complete -c mysqld_safe -l log-error -d 'option: [mysqld] log-error=error'
complete -c mysqld_safe -l help -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqld_safe -l basedir -d 'The path to the MySQL installation directory.  oc o 2. 3'
complete -c mysqld_safe -l core-file-size -d 'The size of the core file that mysqld should be able to create'
complete -c mysqld_safe -l datadir -d 'The path to the data directory.  oc o 2. 3'
complete -c mysqld_safe -l defaults-extra-file -d 'Read this option file in addition to the usual option files'
complete -c mysqld_safe -l defaults-file -d 'Use only the given option file'
complete -c mysqld_safe -l mysqld-safe-log-timestamps -d 'This option controls the format for timestamps in log output produced by mysq…'
complete -c mysqld_safe -l log_timestamps -d 'for the server).  This is the default.  oc o 2. 3'
complete -c mysqld_safe -l malloc-lib -d 'The name of the library to use for memory allocation instead of the system ma…'
complete -c mysqld_safe -l nice -d 'Use the nice program to set the servers scheduling priority to the given value'
complete -c mysqld_safe -l no-defaults -d 'Do not read any option files'
complete -c mysqld_safe -l open-files-limit -d 'The number of files that mysqld should be able to open'
complete -c mysqld_safe -l pid-file -d 'The path name that mysqld should use for its process ID file.  oc o 2. 3'
complete -c mysqld_safe -l plugin-dir -d 'The path name of the plugin directory.  oc o 2. 3'
complete -c mysqld_safe -l port -d 'The port number that the server should use when listening for TCP/IP connecti…'
complete -c mysqld_safe -l skip-kill-mysqld -d 'Do not try to kill stray mysqld processes at startup'
complete -c mysqld_safe -l socket -d 'The Unix socket file that the server should use when listening for local conn…'
complete -c mysqld_safe -l syslog
complete -c mysqld_safe -l skip-syslog
complete -c mysqld_safe -l syslog-tag -d 'For logging to syslog, messages from mysqld_safe and mysqld are written with …'
complete -c mysqld_safe -l timezone -d 'Set the TZ time zone environment variable to the given option value'
complete -c mysqld_safe -l user -d 'Run the mysqld server as the user having the name user_name or the numeric us…'

