# mysqlbinlog
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqlbinlog.1
complete -c mysqlbinlog -l read-from-remote-server -d option
complete -c mysqlbinlog -l host
complete -c mysqlbinlog -l password
complete -c mysqlbinlog -l port
complete -c mysqlbinlog -l protocol
complete -c mysqlbinlog -l socket
complete -c mysqlbinlog -l user
complete -c mysqlbinlog -l verbose -d 'option, mysqlbinlog adds comments stating the compression algorithm used, the…'
complete -c mysqlbinlog -l help
complete -c mysqlbinlog -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqlbinlog -l base64-output -d 'This option determines when events should be displayed encoded as base-64 str…'
complete -c mysqlbinlog -l bind-address -d 'On a computer having multiple network interfaces, use this option to select w…'
complete -c mysqlbinlog -l binlog-row-event-max-size -d 'T{ Command-Line Format T}:T{'
complete -c mysqlbinlog -l character-sets-dir -d 'The directory where character sets are installed.  See Section 10'
complete -c mysqlbinlog -l compress -d 'Compress all information sent between the client and the server if possible'
complete -c mysqlbinlog -l compression-algorithms -d 'The permitted compression algorithms for connections to the server'
complete -c mysqlbinlog -l connection-server-id
complete -c mysqlbinlog -l stop-never -d 'option is also specified to maintain the connection to the server, mysqlbinlo…'
complete -c mysqlbinlog -l database
complete -c mysqlbinlog -s d -d 'This option causes mysqlbinlog to output entries from the binary log (local l…'
complete -c mysqlbinlog -l binlog-do-db -d 'option for mysqld, but can be used to specify only one database.  If'
complete -c mysqlbinlog -l rewrite-db -d 'option, the'
complete -c mysqlbinlog -l debug
complete -c mysqlbinlog -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysqlbinlog -l debug-check -d 'Print some debugging information when the program exits'
complete -c mysqlbinlog -l debug-info -d 'Print debugging information and memory and CPU usage statistics when the prog…'
complete -c mysqlbinlog -l default-auth -d 'A hint about which client-side authentication plugin to use.  See Section 6'
complete -c mysqlbinlog -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysqlbinlog -l defaults-file -d 'Use only the given option file'
complete -c mysqlbinlog -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysqlbinlog -l disable-log-bin
complete -c mysqlbinlog -s D -d 'Disable binary logging'
complete -c mysqlbinlog -l to-last-log -d 'option and are sending the output to the same MySQL server'
complete -c mysqlbinlog -l exclude-gtids -d 'Do not display any of the groups listed in the gtid_set.  oc o 2. 3'
complete -c mysqlbinlog -l force-if-open
complete -c mysqlbinlog -s F -d 'Read binary log files even if they are open or were not closed properly'
complete -c mysqlbinlog -l force-read
complete -c mysqlbinlog -s f -d 'With this option, if mysqlbinlog reads a binary log event that it does not re…'
complete -c mysqlbinlog -l get-server-public-key -d 'Request from the server the public key required for RSA key pair-based passwo…'
complete -c mysqlbinlog -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlbinlog -l hexdump
complete -c mysqlbinlog -s H -d 'Display a hex dump of the log in comments, as described in the section called…'
complete -c mysqlbinlog -s h -d 'Get the binary log from the MySQL server on the given host.  oc o 2. 3'
complete -c mysqlbinlog -l idempotent -d 'Tell the MySQL Server to use idempotent mode while processing updates; this c…'
complete -c mysqlbinlog -l include-gtids -d 'Display only the groups listed in the gtid_set.  oc o 2. 3'
complete -c mysqlbinlog -l local-load
complete -c mysqlbinlog -s l -d 'For data loading operations corresponding to LOAD DATA statements, mysqlbinlo…'
complete -c mysqlbinlog -l load-data-local-dir -d 'option to mysql when processing the output from mysqlbinlog'
complete -c mysqlbinlog -l login-path -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c mysqlbinlog -l no-defaults -d 'Do not read any option files'
complete -c mysqlbinlog -l offset
complete -c mysqlbinlog -s o -d 'Skip the first N entries in the log.  oc o 2. 3'
complete -c mysqlbinlog -l open-files-limit -d 'Specify the number of open file descriptors to reserve.  oc o 2. 3'
complete -c mysqlbinlog -s p -d 'The password of the MySQL account used for connecting to the server'
complete -c mysqlbinlog -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlbinlog -l plugin-dir -d 'The directory in which to look for plugins.  Specify this option if the'
complete -c mysqlbinlog -s P -d 'The TCP/IP port number to use for connecting to a remote server.  oc o 2. 3'
complete -c mysqlbinlog -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysqlbinlog -l print-table-metadata -d 'Print table related metadata from the binary log'
complete -c mysqlbinlog -l raw -d 'By default, mysqlbinlog reads binary log files and writes events in text form…'
complete -c mysqlbinlog -l result-file -d option
complete -c mysqlbinlog -l read-from-remote-source -d 'From MySQL 8. 0. 26, use'
complete -c mysqlbinlog -l read-from-remote-master -d 'COM_BINLOG_DUMP or COM_BINLOG_DUMP_GTID commands by setting the option value …'
complete -c mysqlbinlog -s R -d 'Read the binary log from a MySQL server rather than reading a local log file'
complete -c mysqlbinlog -s r -d 'Without the'
complete -c mysqlbinlog -l require-row-format -d 'Require row-based binary logging format for events'
complete -c mysqlbinlog -l server-id -d 'Display only those events created by the server having the given server ID'
complete -c mysqlbinlog -l server-id-bits -d 'Use only the first N bits of the server_id to identify the server'
complete -c mysqlbinlog -l set-charset -d 'Add a SET NAMES charset_name statement to the output to specify the character…'
complete -c mysqlbinlog -l shared-memory-base-name -d 'On Windows, the shared-memory name to use for connections made using shared m…'
complete -c mysqlbinlog -l short-form
complete -c mysqlbinlog -s s -d 'Display only the statements contained in the log, without any extra informati…'
complete -c mysqlbinlog -l skip-gtids -d 'Do not include the GTIDs from the binary log files in the output dump file'
complete -c mysqlbinlog -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysqlbinlog -l 'ssl*' -d 'Options that begin with'
complete -c mysqlbinlog -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlbinlog -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysqlbinlog -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlbinlog -l start-datetime -d 'Start reading the binary log at the first event having a timestamp equal to o…'
complete -c mysqlbinlog -l start-position
complete -c mysqlbinlog -s j -d 'Start decoding the binary log at the log position N, including in the output …'
complete -c mysqlbinlog -l stop-datetime -d 'Stop reading the binary log at the first event having a timestamp equal to or…'
complete -c mysqlbinlog -l stop-never-slave-server-id -d 'This option is deprecated; expect it to be removed in a future release'
complete -c mysqlbinlog -l stop-position -d 'Stop decoding the binary log at the log position N, excluding from the output…'
complete -c mysqlbinlog -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysqlbinlog -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysqlbinlog -s t -d 'Do not stop at the end of the requested binary log from a MySQL server, but r…'
complete -c mysqlbinlog -s u -d 'The user name of the MySQL account to use when connecting to a remote server'
complete -c mysqlbinlog -s v -d 'Reconstruct row events and display them as commented SQL statements, with tab…'
complete -c mysqlbinlog -l verify-binlog-checksum
complete -c mysqlbinlog -s c -d 'Verify checksums in binary log files.  oc o 2. 3'
complete -c mysqlbinlog -l version
complete -c mysqlbinlog -s V -d 'Display version information and exit'
complete -c mysqlbinlog -l zstd-compression-level -d 'The compression level to use for connections to the server that use the zstd …'
complete -c mysqlbinlog -l binary-mode -d option
complete -c mysqlbinlog -l all-databases
complete -c mysqlbinlog -l events
complete -c mysqlbinlog -l routines -d 'to back up all data, and'
complete -c mysqlbinlog -l master-data -d 'to include the current binary log coordinates in the dump file'

