# mysqlslap
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqlslap.1
complete -c mysqlslap -l create -d or
complete -c mysqlslap -l query -d 'enable you to specify a string containing an SQL statement or a file containi…'
complete -c mysqlslap -l delimiter -d 'option to specify a different delimiter, which enables you to specify stateme…'
complete -c mysqlslap -l help
complete -c mysqlslap -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqlslap -l auto-generate-sql
complete -c mysqlslap -s a -d 'Generate SQL statements automatically when they are not supplied in files or …'
complete -c mysqlslap -l auto-generate-sql-add-autoincrement -d 'Add an AUTO_INCREMENT column to automatically generated tables.  oc o 2. 3'
complete -c mysqlslap -l auto-generate-sql-execute-number -d 'Specify how many queries to generate automatically.  oc o 2. 3'
complete -c mysqlslap -l auto-generate-sql-guid-primary -d 'Add a GUID-based primary key to automatically generated tables.  oc o 2. 3'
complete -c mysqlslap -l auto-generate-sql-load-type -d 'Specify the test load type'
complete -c mysqlslap -l auto-generate-sql-secondary-indexes -d 'Specify how many secondary indexes to add to automatically generated tables'
complete -c mysqlslap -l auto-generate-sql-unique-query-number -d 'How many different queries to generate for automatic tests'
complete -c mysqlslap -l auto-generate-sql-unique-write-number -d 'How many different queries to generate for'
complete -c mysqlslap -l auto-generate-sql-write-number -d 'oc o 2. 3'
complete -c mysqlslap -l commit -d 'How many statements to execute before committing'
complete -c mysqlslap -l compress
complete -c mysqlslap -s C -d 'Compress all information sent between the client and the server if possible'
complete -c mysqlslap -l compression-algorithms -d 'The permitted compression algorithms for connections to the server'
complete -c mysqlslap -l concurrency
complete -c mysqlslap -s c -d 'The number of parallel clients to simulate.  oc o 2. 3'
complete -c mysqlslap -l create-schema -d 'The schema in which to run the tests.  Note If the'
complete -c mysqlslap -l no-drop -d 'option as well.  oc o 2. 3'
complete -c mysqlslap -l csv -d 'Generate output in comma-separated values format'
complete -c mysqlslap -l debug
complete -c mysqlslap -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysqlslap -l debug-check -d 'Print some debugging information when the program exits'
complete -c mysqlslap -l debug-info
complete -c mysqlslap -s T -d 'Print debugging information and memory and CPU usage statistics when the prog…'
complete -c mysqlslap -l default-auth -d 'A hint about which client-side authentication plugin to use.  See Section 6'
complete -c mysqlslap -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysqlslap -l defaults-file -d 'Use only the given option file'
complete -c mysqlslap -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysqlslap -s F -d 'The delimiter to use in SQL statements supplied in files or using command opt…'
complete -c mysqlslap -l detach -d 'Detach (close and reopen) each connection after each N statements'
complete -c mysqlslap -l enable-cleartext-plugin -d 'Enable the mysql_clear_password cleartext authentication plugin'
complete -c mysqlslap -l engine
complete -c mysqlslap -s e -d 'The storage engine to use for creating tables.  oc o 2. 3'
complete -c mysqlslap -l get-server-public-key -d 'Request from the server the RSA public key that it uses for key pair-based pa…'
complete -c mysqlslap -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlslap -l host
complete -c mysqlslap -s h -d 'Connect to the MySQL server on the given host.  oc o 2. 3'
complete -c mysqlslap -l iterations
complete -c mysqlslap -s i -d 'The number of times to run the tests.  oc o 2. 3'
complete -c mysqlslap -l login-path -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c mysqlslap -l no-defaults -d 'Do not read any option files'
complete -c mysqlslap -l number-char-cols
complete -c mysqlslap -s x -d 'The number of VARCHAR columns to use if'
complete -c mysqlslap -l number-int-cols
complete -c mysqlslap -s y -d 'The number of INT columns to use if'
complete -c mysqlslap -l number-of-queries -d 'Limit each client to approximately this many queries'
complete -c mysqlslap -l only-print -d 'Do not connect to databases.  mysqlslap only prints what it would have done'
complete -c mysqlslap -l password
complete -c mysqlslap -s p -d 'The password of the MySQL account used for connecting to the server'
complete -c mysqlslap -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlslap -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlslap -l skip-password1 -d option
complete -c mysqlslap -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlslap -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlslap -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlslap -l pipe
complete -c mysqlslap -s W -d 'On Windows, connect to the server using a named pipe'
complete -c mysqlslap -l plugin-dir -d 'The directory in which to look for plugins.  Specify this option if the'
complete -c mysqlslap -l port
complete -c mysqlslap -s P -d 'For TCP/IP connections, the port number to use.  oc o 2. 3'
complete -c mysqlslap -l post-query -d 'The file or string containing the statement to execute after the tests have c…'
complete -c mysqlslap -l post-system -d 'The string to execute using system() after the tests have completed'
complete -c mysqlslap -l pre-query -d 'The file or string containing the statement to execute before running the tes…'
complete -c mysqlslap -l pre-system -d 'The string to execute using system() before running the tests'
complete -c mysqlslap -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysqlslap -l protocol -d 'The transport protocol to use for connecting to the server'
complete -c mysqlslap -s q -d 'The file or string containing the SELECT statement to use for retrieving data'
complete -c mysqlslap -l shared-memory-base-name -d 'On Windows, the shared-memory name to use for connections made using shared m…'
complete -c mysqlslap -l silent
complete -c mysqlslap -s s -d 'Silent mode.  No output.  oc o 2. 3'
complete -c mysqlslap -l socket
complete -c mysqlslap -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysqlslap -l sql-mode -d 'Set the SQL mode for the client session.  oc o 2. 3'
complete -c mysqlslap -l 'ssl*' -d 'Options that begin with'
complete -c mysqlslap -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlslap -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysqlslap -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlslap -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysqlslap -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysqlslap -l user
complete -c mysqlslap -s u -d 'The user name of the MySQL account to use for connecting to the server'
complete -c mysqlslap -l verbose
complete -c mysqlslap -s v -d 'Verbose mode.  Print more information about what the program does'
complete -c mysqlslap -l version
complete -c mysqlslap -s V -d 'Display version information and exit.  oc o 2. 3'
complete -c mysqlslap -l zstd-compression-level -d 'The compression level to use for connections to the server that use the zstd …'

