# mysql_secure_installation
# Autogenerated from man page /opt/homebrew/share/man/man1/mysql_secure_installation.1
complete -c mysql_secure_installation -l host -d and
complete -c mysql_secure_installation -l port -d 'can be used on the command line and in option files'
complete -c mysql_secure_installation -l help
complete -c mysql_secure_installation -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysql_secure_installation -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysql_secure_installation -l defaults-file -d 'Use only the given option file'
complete -c mysql_secure_installation -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysql_secure_installation -s h -d 'Connect to the MySQL server on the given host.  oc o 2. 3'
complete -c mysql_secure_installation -l no-defaults -d 'Do not read any option files'
complete -c mysql_secure_installation -l password
complete -c mysql_secure_installation -s p -d 'This option is accepted but ignored'
complete -c mysql_secure_installation -s P -d 'For TCP/IP connections, the port number to use.  oc o 2. 3'
complete -c mysql_secure_installation -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysql_secure_installation -l protocol -d 'The transport protocol to use for connecting to the server'
complete -c mysql_secure_installation -l socket
complete -c mysql_secure_installation -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysql_secure_installation -l 'ssl*' -d 'Options that begin with'
complete -c mysql_secure_installation -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysql_secure_installation -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysql_secure_installation -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysql_secure_installation -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysql_secure_installation -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysql_secure_installation -l use-default -d 'Execute noninteractively'
complete -c mysql_secure_installation -l user
complete -c mysql_secure_installation -s u -d 'The user name of the MySQL account to use for connecting to the server'

