# mysqlshow
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqlshow.1
complete -c mysqlshow -l help
complete -c mysqlshow -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqlshow -l bind-address -d 'On a computer having multiple network interfaces, use this option to select w…'
complete -c mysqlshow -l character-sets-dir -d 'The directory where character sets are installed.  See Section 10'
complete -c mysqlshow -l compress
complete -c mysqlshow -s C -d 'Compress all information sent between the client and the server if possible'
complete -c mysqlshow -l compression-algorithms -d 'The permitted compression algorithms for connections to the server'
complete -c mysqlshow -l count -d 'Show the number of rows per table.  This can be slow for non-MyISAM tables'
complete -c mysqlshow -l debug
complete -c mysqlshow -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysqlshow -l debug-check -d 'Print some debugging information when the program exits'
complete -c mysqlshow -l debug-info -d 'Print debugging information and memory and CPU usage statistics when the prog…'
complete -c mysqlshow -l default-character-set -d 'Use charset_name as the default character set.  See Section 10'
complete -c mysqlshow -l default-auth -d 'A hint about which client-side authentication plugin to use.  See Section 6'
complete -c mysqlshow -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysqlshow -l defaults-file -d 'Use only the given option file'
complete -c mysqlshow -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysqlshow -l enable-cleartext-plugin -d 'Enable the mysql_clear_password cleartext authentication plugin'
complete -c mysqlshow -l get-server-public-key -d 'Request from the server the RSA public key that it uses for key pair-based pa…'
complete -c mysqlshow -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlshow -l host
complete -c mysqlshow -s h -d 'Connect to the MySQL server on the given host.  oc o 2. 3'
complete -c mysqlshow -l keys
complete -c mysqlshow -s k -d 'Show table indexes.  oc o 2. 3'
complete -c mysqlshow -l login-path -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c mysqlshow -l no-defaults -d 'Do not read any option files'
complete -c mysqlshow -l password
complete -c mysqlshow -s p -d 'The password of the MySQL account used for connecting to the server'
complete -c mysqlshow -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqlshow -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqlshow -l skip-password1 -d option
complete -c mysqlshow -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqlshow -l 'password1;' -d 'oc o 2. 3'
complete -c mysqlshow -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqlshow -l pipe
complete -c mysqlshow -s W -d 'On Windows, connect to the server using a named pipe'
complete -c mysqlshow -l plugin-dir -d 'The directory in which to look for plugins.  Specify this option if the'
complete -c mysqlshow -l port
complete -c mysqlshow -s P -d 'For TCP/IP connections, the port number to use.  oc o 2. 3'
complete -c mysqlshow -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysqlshow -l protocol -d 'The transport protocol to use for connecting to the server'
complete -c mysqlshow -l shared-memory-base-name -d 'On Windows, the shared-memory name to use for connections made using shared m…'
complete -c mysqlshow -l show-table-type
complete -c mysqlshow -s t -d 'Show a column indicating the table type, as in SHOW FULL TABLES'
complete -c mysqlshow -l socket
complete -c mysqlshow -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysqlshow -l 'ssl*' -d 'Options that begin with'
complete -c mysqlshow -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqlshow -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysqlshow -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqlshow -l status
complete -c mysqlshow -s i -d 'Display extra information about each table.  oc o 2. 3'
complete -c mysqlshow -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysqlshow -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysqlshow -l user
complete -c mysqlshow -s u -d 'The user name of the MySQL account to use for connecting to the server'
complete -c mysqlshow -l verbose
complete -c mysqlshow -s v -d 'Verbose mode.  Print more information about what the program does'
complete -c mysqlshow -l version
complete -c mysqlshow -s V -d 'Display version information and exit.  oc o 2. 3'
complete -c mysqlshow -l zstd-compression-level -d 'The compression level to use for connections to the server that use the zstd …'

