# mysqladmin
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqladmin.1
complete -c mysqladmin -l skip-grant-tables -d 'option.  No password change is applied'
complete -c mysqladmin -l verbose -d 'option is given, the output is like that of SHOW FULL PROCESSLIST'
complete -c mysqladmin -l help
complete -c mysqladmin -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqladmin -l bind-address -d 'On a computer having multiple network interfaces, use this option to select w…'
complete -c mysqladmin -l character-sets-dir -d 'The directory where character sets are installed.  See Section 10'
complete -c mysqladmin -l compress
complete -c mysqladmin -s C -d 'Compress all information sent between the client and the server if possible'
complete -c mysqladmin -l compression-algorithms -d 'The permitted compression algorithms for connections to the server'
complete -c mysqladmin -l connect-timeout -d 'The maximum number of seconds before connection timeout'
complete -c mysqladmin -l count
complete -c mysqladmin -s c -d 'The number of iterations to make for repeated command execution if the'
complete -c mysqladmin -l sleep -d 'option is given.  oc o 2. 3'
complete -c mysqladmin -l debug
complete -c mysqladmin -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysqladmin -l debug-check -d 'Print some debugging information when the program exits'
complete -c mysqladmin -l debug-info -d 'Print debugging information and memory and CPU usage statistics when the prog…'
complete -c mysqladmin -l default-auth -d 'A hint about which client-side authentication plugin to use.  See Section 6'
complete -c mysqladmin -l default-character-set -d 'Use charset_name as the default character set.  See Section 10'
complete -c mysqladmin -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysqladmin -l defaults-file -d 'Use only the given option file'
complete -c mysqladmin -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysqladmin -l enable-cleartext-plugin -d 'Enable the mysql_clear_password cleartext authentication plugin'
complete -c mysqladmin -l force
complete -c mysqladmin -s f -d 'Do not ask for confirmation for the drop db_name command'
complete -c mysqladmin -l get-server-public-key -d 'Request from the server the public key required for RSA key pair-based passwo…'
complete -c mysqladmin -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqladmin -l host
complete -c mysqladmin -s h -d 'Connect to the MySQL server on the given host.  oc o 2. 3'
complete -c mysqladmin -l login-path -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c mysqladmin -l no-beep
complete -c mysqladmin -s b -d 'Suppress the warning beep that is emitted by default for errors such as a fai…'
complete -c mysqladmin -l no-defaults -d 'Do not read any option files'
complete -c mysqladmin -l password
complete -c mysqladmin -s p -d 'The password of the MySQL account used for connecting to the server'
complete -c mysqladmin -l skip-password -d 'option.  oc o 2. 3'
complete -c mysqladmin -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysqladmin -l skip-password1 -d option
complete -c mysqladmin -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysqladmin -l 'password1;' -d 'oc o 2. 3'
complete -c mysqladmin -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysqladmin -l pipe
complete -c mysqladmin -s W -d 'On Windows, connect to the server using a named pipe'
complete -c mysqladmin -l plugin-dir -d 'The directory in which to look for plugins.  Specify this option if the'
complete -c mysqladmin -l port
complete -c mysqladmin -s P -d 'For TCP/IP connections, the port number to use.  oc o 2. 3'
complete -c mysqladmin -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysqladmin -l protocol -d 'The transport protocol to use for connecting to the server'
complete -c mysqladmin -l relative
complete -c mysqladmin -s r -d 'Show the difference between the current and previous values when used with the'
complete -c mysqladmin -l shared-memory-base-name -d 'On Windows, the shared-memory name to use for connections made using shared m…'
complete -c mysqladmin -l show-warnings -d 'Show warnings resulting from execution of statements sent to the server'
complete -c mysqladmin -l shutdown-timeout -d 'The maximum number of seconds to wait for server shutdown'
complete -c mysqladmin -l silent
complete -c mysqladmin -s s -d 'Exit silently if a connection to the server cannot be established.  oc o 2. 3'
complete -c mysqladmin -s i -d 'Execute commands repeatedly, sleeping for delay seconds in between.  The'
complete -c mysqladmin -l socket
complete -c mysqladmin -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysqladmin -l 'ssl*' -d 'Options that begin with'
complete -c mysqladmin -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysqladmin -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysqladmin -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysqladmin -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysqladmin -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysqladmin -l user
complete -c mysqladmin -s u -d 'The user name of the MySQL account to use for connecting to the server'
complete -c mysqladmin -s v -d 'Verbose mode.  Print more information about what the program does.  oc o 2. 3'
complete -c mysqladmin -l version
complete -c mysqladmin -s V -d 'Display version information and exit.  oc o 2. 3'
complete -c mysqladmin -l vertical
complete -c mysqladmin -s E -d 'Print output vertically.  This is similar to'
complete -c mysqladmin -l wait
complete -c mysqladmin -s w -d 'If the connection cannot be established, wait and retry instead of aborting'
complete -c mysqladmin -l zstd-compression-level -d 'The compression level to use for connections to the server that use the zstd …'

