# mysql
# Autogenerated from man page /opt/homebrew/share/man/man1/mysql.1
complete -c mysql -l quick -d option
complete -c mysql -l help
complete -c mysql -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysql -l auto-rehash -d 'Enable automatic rehashing'
complete -c mysql -l disable-auto-rehash -d 'to disable rehashing'
complete -c mysql -l auto-vertical-output -d 'Cause result sets to be displayed vertically if they are too wide for the cur…'
complete -c mysql -l batch
complete -c mysql -s B -d 'Print results using tab as the column separator, with each row on a new line'
complete -c mysql -l raw -d 'option.  oc o 2. 3'
complete -c mysql -l binary-as-hex -d 'When this option is given, mysql displays binary data using hexadecimal notat…'
complete -c mysql -l skip-binary-as-hex -d 'oc o 2. 3'
complete -c mysql -l binary-mode -d 'This option helps when processing mysqlbinlog output that may contain BLOB va…'
complete -c mysql -l bind-address -d 'On a computer having multiple network interfaces, use this option to select w…'
complete -c mysql -l character-sets-dir -d 'The directory where character sets are installed.  See Section 10'
complete -c mysql -l column-names -d 'Write column names in results.  oc o 2. 3'
complete -c mysql -l column-type-info -d 'Display result set metadata'
complete -c mysql -l comments
complete -c mysql -s c -d 'Whether to strip or preserve comments in statements sent to the server'
complete -c mysql -l skip-comments -d '(strip comments), enable with'
complete -c mysql -l compress
complete -c mysql -s C -d 'Compress all information sent between the client and the server if possible'
complete -c mysql -l compression-algorithms -d 'The permitted compression algorithms for connections to the server'
complete -c mysql -l connect-expired-password -d 'Indicate to the server that the client can handle sandbox mode if the account…'
complete -c mysql -l connect-timeout -d 'The number of seconds before connection timeout.  (Default value is 0'
complete -c mysql -l database
complete -c mysql -s D -d 'The database to use.  This is useful primarily in an option file.  oc o 2. 3'
complete -c mysql -l debug
complete -c mysql -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysql -l debug-check -d 'Print some debugging information when the program exits'
complete -c mysql -l debug-info
complete -c mysql -s T -d 'Print debugging information and memory and CPU usage statistics when the prog…'
complete -c mysql -l default-auth -d 'A hint about which client-side authentication plugin to use.  See Section 6'
complete -c mysql -l default-character-set -d 'Use charset_name as the default character set for the client and connection'
complete -c mysql -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysql -l defaults-file -d 'Use only the given option file'
complete -c mysql -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysql -l delimiter -d 'Set the statement delimiter.  The default is the semicolon character (;)'
complete -c mysql -l disable-named-commands -d 'Disable named commands'
complete -c mysql -l dns-srv-name -d 'Specifies the name of a DNS SRV record that determines the candidate hosts to…'
complete -c mysql -l host -d 'option if both are given'
complete -c mysql -l enable-cleartext-plugin -d 'Enable the mysql_clear_password cleartext authentication plugin'
complete -c mysql -l execute
complete -c mysql -s e -d 'Execute the statement and quit'
complete -c mysql -l fido-register-factor -d 'The factor or factors for which FIDO device registration must be performed'
complete -c mysql -l force
complete -c mysql -s f -d 'Continue even if an SQL error occurs.  oc o 2. 3'
complete -c mysql -l get-server-public-key -d 'Request from the server the public key required for RSA key pair-based passwo…'
complete -c mysql -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysql -l histignore -d 'A list of one or more colon-separated patterns specifying statements to ignor…'
complete -c mysql -l syslog -d 'option is given'
complete -c mysql -s h -d 'Connect to the MySQL server on the given host'
complete -c mysql -l html
complete -c mysql -s H -d 'Produce HTML output.  oc o 2. 3'
complete -c mysql -l ignore-spaces
complete -c mysql -s i -d 'Ignore spaces after function names'
complete -c mysql -l init-command -d 'SQL statement to execute after connecting to the server'
complete -c mysql -l line-numbers -d 'Write line numbers for errors.  Disable this with'
complete -c mysql -l skip-line-numbers -d 'oc o 2. 3'
complete -c mysql -l load-data-local-dir -d 'This option affects the client-side LOCAL capability for LOAD DATA operations'
complete -c mysql -l local-infile
complete -c mysql -l login-path -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c mysql -l max-allowed-packet -d 'The maximum size of the buffer for client/server communication'
complete -c mysql -l max-join-size -d 'The automatic limit for rows in a join when using'
complete -c mysql -l safe-updates -d 'oc o 2. 3'
complete -c mysql -l named-commands
complete -c mysql -s G -d 'Enable named mysql commands'
complete -c mysql -l skip-named-commands -d 'to disable named commands.  See the section called “MYSQL CLIENT COMMANDS”'
complete -c mysql -l net-buffer-length -d 'The buffer size for TCP/IP and socket communication.  (Default value is 16KB'
complete -c mysql -l network-namespace -d 'The network namespace to use for TCP/IP connections'
complete -c mysql -l no-auto-rehash
complete -c mysql -s A -d 'This has the same effect as'
complete -c mysql -l skip-auto-rehash
complete -c mysql -l no-beep
complete -c mysql -s b -d 'Do not beep when errors occur.  oc o 2. 3'
complete -c mysql -l no-defaults -d 'Do not read any option files'
complete -c mysql -l one-database
complete -c mysql -s o -d 'Ignore statements except those that occur while the default database is the o…'
complete -c mysql -l pager -d 'Use the given command for paging query output'
complete -c mysql -l skip-pager -d 'the section called “MYSQL CLIENT COMMANDS”, discusses output paging further'
complete -c mysql -l password
complete -c mysql -s p -d 'The password of the MySQL account used for connecting to the server'
complete -c mysql -l skip-password -d 'option.  oc o 2. 3'
complete -c mysql -l password1 -d 'The password for multifactor authentication factor 1 of the MySQL account use…'
complete -c mysql -l skip-password1 -d option
complete -c mysql -l password2 -d 'The password for multifactor authentication factor 2 of the MySQL account use…'
complete -c mysql -l 'password1;' -d 'oc o 2. 3'
complete -c mysql -l password3 -d 'The password for multifactor authentication factor 3 of the MySQL account use…'
complete -c mysql -l pipe
complete -c mysql -s W -d 'On Windows, connect to the server using a named pipe'
complete -c mysql -l plugin-dir -d 'The directory in which to look for plugins.  Specify this option if the'
complete -c mysql -l port
complete -c mysql -s P -d 'For TCP/IP connections, the port number to use.  oc o 2. 3'
complete -c mysql -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysql -l prompt -d 'Set the prompt to the specified format.  The default is mysql>'
complete -c mysql -l protocol -d 'The transport protocol to use for connecting to the server'
complete -c mysql -s q -d 'Do not cache each query result, print each row as it is received'
complete -c mysql -s r -d 'For tabular output, the “boxing” around columns enables one column value to b…'
complete -c mysql -l silent -d 'option is given), special characters are escaped in the output so they can be…'
complete -c mysql -l reconnect -d 'If the connection to the server is lost, automatically try to reconnect'
complete -c mysql -l skip-reconnect -d 'oc o 2. 3'
complete -c mysql -l i-am-a-dummy
complete -c mysql -s U -d 'If this option is enabled, UPDATE and DELETE statements that do not use a key…'
complete -c mysql -l skip-safe-updates -d 'on the command line to override it'
complete -c mysql -l select-limit -d 'The automatic limit for SELECT statements when using'
complete -c mysql -l shared-memory-base-name -d 'On Windows, the shared-memory name to use for connections made using shared m…'
complete -c mysql -l show-warnings -d 'Cause warnings to be shown after each statement if there are any'
complete -c mysql -l sigint-ignore -d 'Ignore SIGINT signals (typically the result of typing Control+C)'
complete -c mysql -s s -d 'Silent mode.  Produce less output'
complete -c mysql -l skip-column-names
complete -c mysql -s N -d 'Do not write column names in results.  oc o 2. 3'
complete -c mysql -s L -d 'Do not write line numbers for errors'
complete -c mysql -l socket
complete -c mysql -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysql -l 'ssl*' -d 'Options that begin with'
complete -c mysql -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysql -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysql -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysql -s j -d 'This option causes mysql to send interactive statements to the system logging…'
complete -c mysql -l table
complete -c mysql -s t -d 'Display output in table format'
complete -c mysql -l tee -d 'Append a copy of output to the given file'
complete -c mysql -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysql -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysql -l unbuffered
complete -c mysql -s n -d 'Flush the buffer after each query.  oc o 2. 3'
complete -c mysql -l user
complete -c mysql -s u -d 'The user name of the MySQL account to use for connecting to the server'
complete -c mysql -l verbose
complete -c mysql -s v -d 'Verbose mode.  Produce more output about what the program does'
complete -c mysql -l version
complete -c mysql -s V -d 'Display version information and exit.  oc o 2. 3'
complete -c mysql -l vertical
complete -c mysql -s E -d 'Print query output rows vertically (one line per column value)'
complete -c mysql -l wait
complete -c mysql -s w -d 'If the connection cannot be established, wait and retry instead of aborting'
complete -c mysql -l xml
complete -c mysql -s X -d 'Produce XML output.  <field name="column_name">NULL</field> The output when'
complete -c mysql -l zstd-compression-level -d 'The compression level to use for connections to the server that use the zstd …'
complete -c mysql -s F -d and

