# mysqld_multi
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqld_multi.1
complete -c mysqld_multi -l defaults-file -d 'option).  N can be any positive integer'
complete -c mysqld_multi -l no-defaults -d 'oc o 2. 3'
complete -c mysqld_multi -l defaults-extra-file -d 'option, if one is given'
complete -c mysqld_multi -l help -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqld_multi -l example -d 'Display a sample option file.  oc o 2. 3'
complete -c mysqld_multi -l log -d 'Specify the name of the log file'
complete -c mysqld_multi -l mysqladmin -d 'The mysqladmin binary to be used to stop servers.  oc o 2. 3'
complete -c mysqld_multi -l mysqld -d 'The mysqld binary to be used'
complete -c mysqld_multi -l no-log -d 'Print log information to stdout rather than to the log file'
complete -c mysqld_multi -l password -d 'The password of the MySQL account to use when invoking mysqladmin'
complete -c mysqld_multi -l silent -d 'Silent mode; disable warnings.  oc o 2. 3'
complete -c mysqld_multi -l tcp-ip -d 'Connect to each MySQL server through the TCP/IP port instead of the Unix sock…'
complete -c mysqld_multi -l user -d 'The user name of the MySQL account to use when invoking mysqladmin.  oc o 2'
complete -c mysqld_multi -l verbose -d 'Be more verbose.  oc o 2. 3'
complete -c mysqld_multi -l version -d 'Display version information and exit.  Some notes about mysqld_multi: oc o 2'
complete -c mysqld_multi -l pid-file -d 'option is very important if you are using mysqld_safe to start mysqld (for ex…'

