# mysql_config_editor
# Autogenerated from man page /opt/homebrew/share/man/man1/mysql_config_editor.1
complete -c mysql_config_editor -l login-path -d 'option to indicate explicitly which login path to use.  oc o 2. 3'
complete -c mysql_config_editor -l no-defaults -d 'option is used'
complete -c mysql_config_editor -l all -d 'to display all login paths or'
complete -c mysql_config_editor -l help
complete -c mysql_config_editor -s '?' -d 'Display a general help message and exit'
complete -c mysql_config_editor -l debug
complete -c mysql_config_editor -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysql_config_editor -l verbose
complete -c mysql_config_editor -s v -d 'Verbose mode.  Print more information about what the program does'
complete -c mysql_config_editor -l version
complete -c mysql_config_editor -s V -d 'Display version information and exit'
complete -c mysql_config_editor -s G
complete -c mysql_config_editor -l host
complete -c mysql_config_editor -l password
complete -c mysql_config_editor -l port
complete -c mysql_config_editor -l socket
complete -c mysql_config_editor -l user -d options
complete -c mysql_config_editor -s h
complete -c mysql_config_editor -s p
complete -c mysql_config_editor -s P
complete -c mysql_config_editor -s S
complete -c mysql_config_editor -s u
complete -c mysql_config_editor -l warn
complete -c mysql_config_editor -s w
complete -c mysql_config_editor -l skip-warn -d 'to disable it.  oc o 2. 3'

