# mysql_ssl_rsa_setup
# Autogenerated from man page /opt/homebrew/share/man/man1/mysql_ssl_rsa_setup.1
complete -c mysql_ssl_rsa_setup -l datadir -d 'to specify where to create the files, and'
complete -c mysql_ssl_rsa_setup -l verbose -d 'to see the openssl commands that mysql_ssl_rsa_setup executes'
complete -c mysql_ssl_rsa_setup -l ssl -d '(possibly along with ssl_cipher)'
complete -c mysql_ssl_rsa_setup -l ssl-ca
complete -c mysql_ssl_rsa_setup -l ssl-cert
complete -c mysql_ssl_rsa_setup -l ssl-key -d 'options at startup to name the ca. pem, server-cert. pem, and server-key'
complete -c mysql_ssl_rsa_setup -l help -d '? Display a help message and exit.  oc o 2. 3'
complete -c mysql_ssl_rsa_setup -l suffix -d 'The suffix for the Common Name attribute in X. 509 certificates'
complete -c mysql_ssl_rsa_setup -l uid
complete -c mysql_ssl_rsa_setup -s v -d 'The name of the user who should be the owner of any created files'
complete -c mysql_ssl_rsa_setup -l version
complete -c mysql_ssl_rsa_setup -s V -d 'Display version information and exit'

