# mysqldumpslow
# Autogenerated from man page /opt/homebrew/share/man/man1/mysqldumpslow.1
complete -c mysqldumpslow -s a -d and
complete -c mysqldumpslow -s n -d options
complete -c mysqldumpslow -l help -d 'Display a help message and exit.  oc o 2. 3'
complete -c mysqldumpslow -l debug
complete -c mysqldumpslow -s d -d 'Run in debug mode'
complete -c mysqldumpslow -s g
complete -c mysqldumpslow -s h
complete -c mysqldumpslow -s i
complete -c mysqldumpslow -s l
complete -c mysqldumpslow -s r
complete -c mysqldumpslow -s s
complete -c mysqldumpslow -s t
complete -c mysqldumpslow -l verbose
complete -c mysqldumpslow -s v -d 'Verbose mode.  Print more information about what the program does'

