# mysql_upgrade
# Autogenerated from man page /opt/homebrew/share/man/man1/mysql_upgrade.1
complete -c mysql_upgrade -l protocol -d 'option forces a connection using TCP/IP rather than the Unix socket file'
complete -c mysql_upgrade -l upgrade-system-tables -d 'option, mysql_upgrade processes all tables in all user schemas as necessary'
complete -c mysql_upgrade -l force -d option
complete -c mysql_upgrade -l skip-sys-schema -d 'option, mysql_upgrade installs the sys schema if it is not installed, and upg…'
complete -c mysql_upgrade -l help -d 'Display a short help message and exit.  oc o 2. 3'
complete -c mysql_upgrade -l bind-address -d 'On a computer having multiple network interfaces, use this option to select w…'
complete -c mysql_upgrade -l character-sets-dir -d 'The directory where character sets are installed.  See Section 10'
complete -c mysql_upgrade -l compress
complete -c mysql_upgrade -s C -d 'Compress all information sent between the client and the server if possible'
complete -c mysql_upgrade -l compression-algorithms -d 'The permitted compression algorithms for connections to the server'
complete -c mysql_upgrade -l debug
complete -c mysql_upgrade -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c mysql_upgrade -l debug-check -d 'Print some debugging information when the program exits.  oc o 2. 3'
complete -c mysql_upgrade -l debug-info
complete -c mysql_upgrade -s T -d 'Print debugging information and memory and CPU usage statistics when the prog…'
complete -c mysql_upgrade -l default-auth -d 'A hint about which client-side authentication plugin to use.  See Section 6'
complete -c mysql_upgrade -l default-character-set -d 'Use charset_name as the default character set.  See Section 10'
complete -c mysql_upgrade -l defaults-extra-file -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c mysql_upgrade -l defaults-file -d 'Use only the given option file'
complete -c mysql_upgrade -l defaults-group-suffix -d 'Read not only the usual option groups, but also groups with the usual names a…'
complete -c mysql_upgrade -l get-server-public-key -d 'Request from the server the public key required for RSA key pair-based passwo…'
complete -c mysql_upgrade -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysql_upgrade -l host
complete -c mysql_upgrade -s h -d 'Connect to the MySQL server on the given host.  oc o 2. 3'
complete -c mysql_upgrade -l login-path -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c mysql_upgrade -l max-allowed-packet -d 'The maximum size of the buffer for client/server communication'
complete -c mysql_upgrade -l net-buffer-length -d 'The initial size of the buffer for client/server communication'
complete -c mysql_upgrade -l no-defaults -d 'Do not read any option files'
complete -c mysql_upgrade -l password
complete -c mysql_upgrade -s p -d 'The password of the MySQL account used for connecting to the server'
complete -c mysql_upgrade -l skip-password -d 'option.  oc o 2. 3'
complete -c mysql_upgrade -l pipe
complete -c mysql_upgrade -s W -d 'On Windows, connect to the server using a named pipe'
complete -c mysql_upgrade -l plugin-dir -d 'The directory in which to look for plugins.  Specify this option if the'
complete -c mysql_upgrade -l port
complete -c mysql_upgrade -s P -d 'For TCP/IP connections, the port number to use.  oc o 2. 3'
complete -c mysql_upgrade -l print-defaults -d 'Print the program name and all options that it gets from option files'
complete -c mysql_upgrade -l shared-memory-base-name -d 'On Windows, the shared-memory name to use for connections made using shared m…'
complete -c mysql_upgrade -l socket
complete -c mysql_upgrade -s S -d 'For connections to localhost, the Unix socket file to use, or, on Windows, th…'
complete -c mysql_upgrade -l 'ssl*' -d 'Options that begin with'
complete -c mysql_upgrade -l ssl -d 'specify whether to connect to the server using encryption and indicate where …'
complete -c mysql_upgrade -l ssl-fips-mode -d 'Controls whether to enable FIPS mode on the client side.  The'
complete -c mysql_upgrade -l ssl-xxx -d 'options in that it is not used to establish encrypted connections, but rather…'
complete -c mysql_upgrade -l tls-ciphersuites -d 'The permissible ciphersuites for encrypted connections that use TLSv1. 3'
complete -c mysql_upgrade -l tls-version -d 'The permissible TLS protocols for encrypted connections'
complete -c mysql_upgrade -s s -d 'Upgrade only the system tables in the mysql schema, do not upgrade user schem…'
complete -c mysql_upgrade -l user
complete -c mysql_upgrade -s u -d 'The user name of the MySQL account to use for connecting to the server'
complete -c mysql_upgrade -l verbose -d 'Verbose mode.  Print more information about what the program does.  oc o 2. 3'
complete -c mysql_upgrade -l version-check
complete -c mysql_upgrade -s k -d 'Check the version of the server to which mysql_upgrade is connecting to verif…'
complete -c mysql_upgrade -l skip-version-check -d 'oc o 2. 3'
complete -c mysql_upgrade -l write-binlog -d 'By default, binary logging by mysql_upgrade is disabled'
complete -c mysql_upgrade -l zstd-compression-level -d 'The compression level to use for connections to the server that use the zstd …'

