# mysql_config
# Autogenerated from man page /opt/homebrew/share/man/man1/mysql_config.1
complete -c mysql_config -l cflags -d 'C Compiler flags to find include files and critical compiler flags and define…'
complete -c mysql_config -l include -d 'for more portable options that contain only include paths.  oc o 2. 3'
complete -c mysql_config -l cxxflags -d Like
complete -c mysql_config -l libs -d 'Libraries and options required to link with the MySQL client library.  oc o 2'
complete -c mysql_config -l libs_r -d 'Libraries and options required to link with the thread-safe MySQL client libr…'
complete -c mysql_config -l plugindir -d 'The default plugin directory path name, defined when configuring MySQL'
complete -c mysql_config -l port -d 'The default TCP/IP port number, defined when configuring MySQL.  oc o 2. 3'
complete -c mysql_config -l socket -d 'The default Unix socket file, defined when configuring MySQL.  oc o 2. 3'
complete -c mysql_config -l variable -d 'Display the value of the named configuration variable'
complete -c mysql_config -l version -d 'Version number for the MySQL distribution'

