# ncurses5.4-config
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/ncurses5.4-config.1
complete -c 'ncurses5.4-config' -l -prefix -d 'Reports package-prefix ncurses5. 4-config was installed with'
complete -c 'ncurses5.4-config' -l -exec-prefix -d 'Reports executable-prefix ncurses5. 4-config was installed with'
complete -c 'ncurses5.4-config' -l -cflags -d 'Reports C compiler flags needed to compile with ncurses'
complete -c 'ncurses5.4-config' -l -libs -d 'Reports libraries needed to link with ncurses'
complete -c 'ncurses5.4-config' -l -version -d 'Reports release+patchdate version ncurses5. 4-config was installed with'
complete -c 'ncurses5.4-config' -l -abi-version -d 'Reports ABI version ncurses5. 4-config was installed with'
complete -c 'ncurses5.4-config' -l -mouse-version -d 'Reports mouse-interface version ncurses5. 4-config was installed with'
complete -c 'ncurses5.4-config' -l -bindir -d 'Reports directory containing ncurses5. 4-config programs'
complete -c 'ncurses5.4-config' -l -datadir -d 'Reports directory containing ncurses5. 4-config data'
complete -c 'ncurses5.4-config' -l -libdir -d 'Reports directory containing ncurses5. 4-config libraries'
complete -c 'ncurses5.4-config' -l -mandir -d 'Reports directory containing ncurses5. 4-config manpages'
complete -c 'ncurses5.4-config' -l -terminfo -d 'Reports $TERMINFO terminfo database path'
complete -c 'ncurses5.4-config' -l -terminfo-dirs -d 'Reports $TERMINFO_DIRS directory list'
complete -c 'ncurses5.4-config' -l -termpath -d 'Reports $TERMPATH termcap list El EXIT STATUS -std'

