# ntfs.util
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ntfs.util.8
complete -c 'ntfs.util' -s k -d 'Get the UUID key for the NTFS file system at device'
complete -c 'ntfs.util' -s m -d 'Mount the NTFS file system located on device onto mountpoint with the flags m…'
complete -c 'ntfs.util' -s p -d 'Probe the device for an NTFS file system using the flags mountflag1 mountflag2'
complete -c 'ntfs.util' -s u -d 'Unmount the NTFS file system located at device and mounted on mountpoint'

