# opj_dump
# Autogenerated from man page /opt/homebrew/share/man/man1/opj_dump.1
complete -c opj_dump -s i -d '(jpeg2000 input file name)'
complete -c opj_dump -o ImgDir -d '(directory containing jpeg2000 input files) AUTHORS Copyright (c) 2010, Mathi…'

