# osql
# Autogenerated from man page /opt/homebrew/share/man/man1/osql.1
complete -c osql -s S -d 'the Data Source Name to which to connect, as known to odbc. ini Ns'
complete -c osql -s U -d 'database login name'
complete -c osql -s P -d 'database password'
complete -c osql -s I -d 'override odbc. ini file location.  El EXAMPLE If you have an odbc'

