# photosctl
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/photosctl.1
complete -c photosctl -s h -l help -d 'Convenience alias for help,'
complete -c photosctl -l version -d 'Show the version of photosctl'

