# php-fpm
# Autogenerated from man page /opt/homebrew/share/man/man8/php-fpm.8
complete -c php-fpm -s C -d 'Do not chdir to the script\'s directory'
complete -c php-fpm -s c -d 'Look for  php. ini file in the directory R path or use the specified R file'
complete -c php-fpm -s n -d 'No  php. ini file will be used'
complete -c php-fpm -s d -d 'Define INI entry R foo with value R bar'
complete -c php-fpm -s e -d 'Generate extended information for debugger/profiler'
complete -c php-fpm -s h -d 'This help'
complete -c php-fpm -s i -d 'PHP information and configuration'
complete -c php-fpm -s m -d 'Show compiled in modules'
complete -c php-fpm -s v -d 'Version number  --prefix path'
complete -c php-fpm -s p -d 'Specify alternative prefix path (the default is /opt/homebrew/Cellar/php/8. 1'
complete -c php-fpm -s g -d 'Specify the PID file location'
complete -c php-fpm -s y -d 'Specify alternative path to FastCGI process manager configuration file (the d…'
complete -c php-fpm -s t -d 'Test FPM configuration file and exit If called twice (-tt), the configuration…'
complete -c php-fpm -s D -d 'Force to run in background and ignore daemonize option from configuration file'
complete -c php-fpm -s F -d 'Force to stay in foreground and ignore daemonize option from configuration fi…'
complete -c php-fpm -s O -d 'Force output to stderr in nodaemonize even if stderr is not a TTY'
complete -c php-fpm -l php-ini
complete -c php-fpm -l no-php-ini
complete -c php-fpm -l define
complete -c php-fpm -l help
complete -c php-fpm -l info
complete -c php-fpm -l modules
complete -c php-fpm -l version
complete -c php-fpm -l prefix
complete -c php-fpm -l pid
complete -c php-fpm -l fpm-config
complete -c php-fpm -l test
complete -c php-fpm -l daemonize
complete -c php-fpm -l nodaemonize
complete -c php-fpm -l force-stderr
complete -c php-fpm -l allow-to-run-as-root
complete -c php-fpm -s R -d 'Allow pool to run as root (disabled by default) FILES'

