# profiles
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/profiles.1
complete -c profiles -o type -d 'The profile_type can be one of either: "configuration", "provisioning", "boot…'
complete -c profiles -o path -d 'A file path or "-" to represent stdout'
complete -c profiles -o user -d 'An OD short user name'
complete -c profiles -o uuid -d 'A canonical form UUID to specify a profile\'s PayloadUUID, such as 5A15247B-89…'
complete -c profiles -o identifier -d 'A profile identifier (PayloadIdentifier) to specify a profile'
complete -c profiles -o output -d 'The output path location'
complete -c profiles -o password -d 'An optional password used when removing a configuration profile which require…'
complete -c profiles -o forced -d 'This will prevent confirmation requests, and when trying to remove all config…'
complete -c profiles -o all -d 'For configuration profiles, when running as root, the use of this option with…'
complete -c profiles -o cached -d 'A flag to indicate that information should only be obtained from the local ca…'
complete -c profiles -o verbose -d 'Display additional information'

