# rpc.statd
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/rpc.statd.8
complete -c 'rpc.statd' -s d -d 'Sets the logging level to the maximum'
complete -c 'rpc.statd' -s n -d 'Send SM_NOTIFY messages to notify any hosts of a restart'
complete -c 'rpc.statd' -s l -d 'List each host (and its status) in the status file'
complete -c 'rpc.statd' -s L -d 'List each host (and its status) in the status file and then continue to watch…'
complete -c 'rpc.statd' -s N -d 'Clear the "needs notification" status for hostname so the statd'

