# shazam-signature
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-signature.1
complete -c shazam-signature -s i -l input -d 'Path to an audio or video file to generate a shazam signature from'
complete -c shazam-signature -s o -l output -d 'Path to save the new shazam signature file'

