# shazam-custom-catalog-display
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-custom-catalog-display.1
complete -c shazam-custom-catalog-display -s i -l input -d 'Path to an existing custom catalog file to be displayed'

