# shazam-custom-catalog-update
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-custom-catalog-update.1
complete -c shazam-custom-catalog-update -s i -l input -d 'Path to the existing custom catalog file to update'
complete -c shazam-custom-catalog-update -s m -l media-items -d 'Path to a '
complete -c shazam-custom-catalog-update -s o -l output -d 'Path to save the updated custom catalog file'
complete -c shazam-custom-catalog-update -s s -l signature-asset -d 'Path to an audio, video or shazam signature file'

