# shazam-custom-catalog-create
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-custom-catalog-create.1
complete -c shazam-custom-catalog-create -s m -l media-items -d 'Path to a '
complete -c shazam-custom-catalog-create -s o -l output -d 'Path to save a new custom catalog file'
complete -c shazam-custom-catalog-create -s s -l signature-asset -d 'Path to an audio, video or shazam signature file'

