# shazam-custom-catalog-remove
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-custom-catalog-remove.1
complete -c shazam-custom-catalog-remove -s i -l input -d 'Path to an existing custom catalog file to remove a signature and/or media it…'
complete -c shazam-custom-catalog-remove -s m -l media-item-ids -d 'Comma separated list of media item IDs associated with a signature in a custo…'
complete -c shazam-custom-catalog-remove -s o -l output -d 'Path to save a new custom catalog file'
complete -c shazam-custom-catalog-remove -s s -l signature-id -d 'Unique identifier of a signature in a custom catalog'

