# siritts
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/siritts.1
complete -c siritts -s l -d language
complete -c siritts -s t -d text
complete -c siritts -s n -d 'voice name, e. g.  nora'
complete -c siritts -s p -d 'Indicate if this request is privacy sensitive'
complete -c siritts -s o -d 'If set, audio will be written to the output file instead of being played loud'
complete -c siritts -l nonlocal -d 'By default we list locally available assets only'
complete -c siritts -s a -d 'lists all assets, regardless of availability'
complete -c siritts -l tab -d 'by default, output is formatted in aligned columns, with this option, output …'
complete -c siritts -l clobber -d 'Allow more than 3 assets to be downloaded at once'
complete -c siritts -l immediately -d 'Recover space immediately instead of leaving the decision to the OS (a distin…'
complete -c siritts -s r -d 'Specifies the directory containing the assets'
complete -c siritts -l stdio -d 'Listens for requests on standard input'
complete -c siritts -l url -d 'Use an explicitly defined server URL (e. g.  for a local mirror)'
complete -c siritts -l production -d 'Use production asset server'
complete -c siritts -l livability -d 'Use livability asset server'
complete -c siritts -l staging -d 'Use staging asset server'
complete -c siritts -l reset -d 'Reset to default asset server'
complete -c siritts -s s -d 'Specify the download source (mobile or trial) El asset show-server Xo verbose…'
complete -c siritts -s v -d 'List full URLs for production, livability, and staging servers'
complete -c siritts -s L -d 'Specify the language(s) we\'re interested in'
complete -c siritts -l male -d 'Specify the gender(s) we\'re interested in'
complete -c siritts -s q -d 'Specify the quality(s) we\'re interested in among -tag -width indent compact p…'
complete -c siritts -s 1 -d 'Only use the top match among the assets found'
complete -c siritts -l obsolete -d 'By default, we only list the newest version of an asset'

