# uname
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/uname.1
complete -c uname -s a -d 'Behave as though the options m , n , r , s, and v were specified'
complete -c uname -s m -d 'Write the type of the current hardware platform to standard output'
complete -c uname -s n -d 'Write the name of the system to standard output'
complete -c uname -s o -d 'This is a synonym for the s option, for compatibility with other systems'
complete -c uname -s p -d 'Write the type of the machine processor architecture to standard output'
complete -c uname -s r -d 'Write the current release level of the operating system to standard output'
complete -c uname -s s -d 'Write the name of the operating system implementation to standard output'
complete -c uname -s v -d 'Write the version level of this release of the operating system to standard o…'

