# unbound-checkconf
# Autogenerated from man page /opt/homebrew/share/man/man8/unbound-checkconf.8
complete -c unbound-checkconf -s h -d 'Show the version and commandline option help'
complete -c unbound-checkconf -s f -d 'Print full pathname, with chroot applied to it.   Use with the -o option'
complete -c unbound-checkconf -s o -d 'If given, after checking the config file the value of this option is printed …'

