# unbound
# Autogenerated from man page /opt/homebrew/share/man/man8/unbound.8
complete -c unbound -s h -d 'Show the version number and commandline option help, and exit'
complete -c unbound -s c -d 'Set the config file with settings for Unbound to read instead of reading the …'
complete -c unbound -s d -d 'Debug flag: do not fork into the background, but stay attached to the console'
complete -c unbound -s p -d 'Don\'t use a pidfile'
complete -c unbound -s v -d 'Increase verbosity.  If given multiple times, more information is logged'
complete -c unbound -s V -d 'Show the version number and build options, and exit.  SEE ALSO unbound'

