# what
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/what.1
complete -c what -s q -d 'Only output the match text, rather than formatting it'
complete -c what -s s -d 'Stop searching each file after the first match'

