# word-list-compress
# Autogenerated from man page /opt/homebrew/share/man/man1/word-list-compress.1
complete -c word-list-compress -s c -d 'compress the plain text word list read from standard input'
complete -c word-list-compress -s d -d 'decompress the compressed word list read from standard input'

